name: Regression Tests
on:
  pull_request:
    branches: [main]

env:
  lambatestAccessKey: ${{ secrets.LAMBATESTACCESSKEY }}
  lambatestUsername: ${{ secrets.LAMBATESTUSERNAME }}
  url: ${{ secrets.URL }}

jobs:
  regression-test:
    environment: qa
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Selenium tests
        run: mvn clean test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-report
          path: target/test-report.html
          retention-days: 30